export const BACKGROUND_FADE_DELAY = 1.5;
export const BACKGROUND_FADE_DURATION = 2;
export const HERO_FADE_DELAY =
  BACKGROUND_FADE_DELAY + BACKGROUND_FADE_DURATION - 1;
export const HERO_FADE_DURATION = 1;
export const CONNECT_HUB_WITH_NODES_DELAY =
  BACKGROUND_FADE_DELAY + BACKGROUND_FADE_DURATION + 0.5;
